name: riskmobile
description: RiskMobile - Plataforma móvil SaaS de evaluación financiera y gestión de asesoría crediticia.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^3.9.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0
  
  flutter_riverpod: ^2.6.1
  
  go_router: ^14.8.1
  
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^1.2.0
  fl_chart: ^0.70.2
  
  local_auth: ^2.3.0
  
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  
  intl: ^0.19.0
  uuid: ^4.5.1
  shared_preferences: ^2.5.2
  
  url_launcher: ^6.3.1
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
